import orchestrator from "tests/orchestrator";
import { version as uuidVersion } from "uuid";
import setCookieParser from "set-cookie-parser";
import Decimal from "decimal.js";

beforeAll(async () => {
  await orchestrator.waitForAllServices();
  await orchestrator.clearDatabase();
  await orchestrator.runPendingMigrations();
});

describe("GET to /api/v1/asset_positions/[id]", () => {
  describe("Anonymous User", () => {
    test("with no session", async () => {
      const getResponse = await getAssetPositionById("", {});
      expect(getResponse.status).toBe(401);

      const getResponseBody = await getResponse.json();
      expect(getResponseBody).toEqual({
        name: "UnauthorizedError",
        message: "Unable to Find a Valid Session",
        action: "Please, review session information",
        status_code: 401,
      });
    });
    test("with invalid session", async () => {
      const invalidSession = {
        token:
          "3e5b70f82f559ef2b3596d291548f1e25f2ffb42c645b71cb7fb6b220f432482e8c6fd50be7baefb9ab2aab991d1f841",
      };
      const getResponse = await getAssetPositionById("", invalidSession);

      expect(getResponse.status).toBe(401);

      const getResponseBody = await getResponse.json();
      expect(getResponseBody).toEqual({
        name: "UnauthorizedError",
        message: "Unable to Find a Valid Session",
        action: "Please, review session information",
        status_code: 401,
      });
      // Set-Cookie assertions
      const parsedSetCookie = setCookieParser(getResponse, {
        map: true,
      });

      expect(parsedSetCookie.session_id).toEqual({
        name: "session_id",
        value: "invalid",
        maxAge: -1,
        path: "/",
        httpOnly: true,
      });
    });
  });
  describe("Defined User", () => {
    test("with a valid BUY transactions", async () => {
      const randTransaction = await orchestrator.createRandTransaction({
        transaction_type_key: "BUY",
      });

      console.log("randTransaction");
      console.log(randTransaction);
      // Should have at least one generated by the transaction above
      const [ap1] = await orchestrator.getUserAssetPositions(
        randTransaction.user_id,
      );
      console.log("ap1");
      console.log(ap1);
      const testSession = await orchestrator.createSession(
        randTransaction.user_id,
      );

      const getResponse = await getAssetPositionById(ap1.id, testSession);

      expect(getResponse.status).toBe(200);

      const assetPosition = await getResponse.json();

      // Transaction 1:
      expect(uuidVersion(assetPosition.id)).toBe(4);
      expect(assetPosition.user_id).toBe(randTransaction.user_id);
      expect(assetPosition.asset_id).toBe(randTransaction.asset_id);
      expect(assetPosition.quantity).toBe(randTransaction.quantity);
      expect(
        new Decimal(assetPosition.total_cost).equals(
          new Decimal(randTransaction.quantity).times(
            new Decimal(randTransaction.unit_price),
          ),
        ),
      ).toBe(true);
      expect(assetPosition.avg_cost).toBe(randTransaction.unit_price);

      expect(Date.parse(assetPosition.created_date)).not.toBeNaN();
      expect(Date.parse(assetPosition.updated_date)).not.toBeNaN();
    });
  });
});

async function getAssetPositionById(position_id, sessionObject) {
  return await fetch(
    `http://localhost:3000/api/v1/asset_positions/${position_id}`,
    {
      headers: {
        "Content-Type": "application/json",
        Cookie: `session_id=${sessionObject.token}`,
      },
    },
  );
}
